spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    proposal:
      pending: proposal-pending.ms-notification

aws:
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}
